[server]
headless = true
port = 8501

[theme]
primaryColor = "#636EFA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
